import React, { useEffect, useState } from 'react'
import Head from 'next/head'
import Link from 'next/link';





export default function listing() {
    const [blogs , setBlogs]=useState([]);
    useEffect(()=>{
        fetch('http://localhost:8000/api/user-list').then((a)=>{
        return a.json();})
        .then((parsed)=>{
            setBlogs(parsed);
        })
    },[])

    const onclickHandler=(id)=>{
        const data={id};
        fetch("http://localhost:8000/api/user-delete", {
            method: "POST", // or 'PUT'
            headers: {
                "Content-Type": "application/json",
            },
            body: JSON.stringify(data),
            })
            .then(response => response.text())
            .then(data => {
            console.log('Success : ' , data);
                
            alert("Deleted Successfully");
            })
            .catch((error) => {
            console.log('Error : ' , error);
            });
    }

    
  return (<>
  <Head>
        <title>Listing</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
  </Head>
  <div className="row">
    <div className="col-md-6">

    

    <div class="card">
        <div class="card-body">
            <h5 class="card-title">Listing</h5>
            <div className="row">
                <div className="col-md-12">
                <table className="table">
                    <thead>
                        <tr>
                        <th scope="col">#</th>
                        <th scope="col">Name</th>
                        <th scope="col">Email</th>
                        <th scope="col">Phone</th>
                        <th scope="col">Edit</th>
                        <th scope="col">Delete</th>
                        </tr>
                    </thead>
                    <tbody>
                    {blogs.map((blogItem, index)=>{
                            return (
                            <tr key={index}>
                            <th>{blogItem.id}</th>
                            <td>{blogItem.name}</td>
                            <td>{blogItem.email}</td>
                            <td>{blogItem.phone}</td>
                            <td><Link href={`/update/${blogItem.id}`}> <i class="fa fa-pencil-square-o" aria-hidden="true"></i></Link></td>
                            <td><i class="fa fa-trash" aria-hidden="true" onClick={() => onclickHandler(blogItem.id)} ></i></td>
                            </tr>
                            
                            );
                    })}
                        
                    </tbody>
                    </table>
                </div>
            </div>
            
            
        </div>
        </div>
    </div>
  </div>
  </>
  )
}
