import React, { useState } from 'react'
import Head from 'next/head'

export default function signup() {
    const [name , setName]=useState("");
    const [email, setEmail]=useState("");
    const [phone , setPhone]=useState("");
    const [password, setPassword]=useState("");

    const onchangeHandler=(e)=>{
        if(e.target.name=="name")
        {
            setName(e.target.value);
        }
        else if(e.target.name=="email")
        {
            setEmail(e.target.value);
        }
        else if(e.target.name=="phone")
        {
            setPhone(e.target.value);
        }
        else if(e.target.name=="password")
        {
            setPassword(e.target.value);
        }
    }
    const [error, setError] = useState('');
    const [success, setSuccess] = useState('');
    const onsubmitHandler=(e)=>{
        e.preventDefault();
        
        const data={name , email ,phone , password};
        if(name=="")
        {
            setError("Please enter your name");
        }
        else if(email=="")
        {
            setError("Please enter your email");
        }
        else if(phone=="")
        {
            setError("Please enter your phone");
        }
        else if(password=="")
        {
            setError("Please enter your password");
        }
        else 
        {
            // setSuccess("All field Done");
            fetch("http://localhost:8000/api/user-store", {
            method: "POST", // or 'PUT'
            headers: {
                "Content-Type": "application/json",
            },
            body: JSON.stringify(data),
            })
            .then(response => response.text())
            .then(data => {
            console.log('Success : ' , data);
                setName("");
                setEmail("");
                setPhone("");
                setPassword("");
            alert("Submitted Successfully");
            })
            .catch((error) => {
            console.log('Error : ' , error);
            });
        }
        // console.log(name+" "+email+" "+phone+" "+password);
        
    }
  return (<>
  <Head>
        <title>Sign Up</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
  </Head>
  <div className="row">
    <div className="col-md-6">
    <div className="card">
        <div className="card-body">
            <h5 className="card-title">Sign Up</h5>
                {success 
                       ? 
                    <span className="flex items-center text-sm font-bold text-green-700"> 
                        
                         {success}
                    </span> 
                       : 
                    <span className="flex items-center text-sm font-bold text-red-800">
                    
                          {error} 
                    </span>
                }
            
            <form onSubmit={onsubmitHandler}>
            <div className="row">
                <div className="col-md-12">
                    <div className="mb-3">
                        <label for="exampleFormControlInput1" className="form-label">Name</label>
                        <input type="text" className="form-control" name="name" value={name} onChange={onchangeHandler} placeholder="Enter Name" />
                    </div>
                    <div className="mb-3">
                        <label for="exampleFormControlInput1" className="form-label">Email</label>
                        <input type="email" className="form-control" name="email" value={email} onChange={onchangeHandler} placeholder="Enter Email" />
                    </div>
                    <div className="mb-3">
                        <label for="exampleFormControlInput1" className="form-label">Phone No</label>
                        <input type="tel" className="form-control" name="phone" value={phone} onChange={onchangeHandler} placeholder="Enter Phone No" />
                    </div>
                    <div className="mb-3">
                        <label for="exampleFormControlInput1" className="form-label">Password</label>
                        <input type="password" className="form-control" name="password" value={password} onChange={onchangeHandler} placeholder="Create Password" />
                    </div>
                    <div className="mb-3">
                        <button type="submit" className="btn btn-success">Submit</button>
                    </div>
                </div>
            </div>
            </form>
            
        </div>
        </div>
    </div>
  </div>
  </>
    
  )
}
