import React, { useState, useEffect } from 'react'
import Head from 'next/head'


export default function update() {
    const [blogs , setBlogs]=useState([]);
    useEffect(()=>{
        fetch('http://localhost:8000/api/user-edit/2').then((a)=>{
        return a.json();})
        .then((parsed)=>{
            setBlogs(parsed);
        })
    },[])

    const [id , setId]=useState(2);
    const [name , setName]=useState(blogs.name);
    const [email, setEmail]=useState(blogs.email);
    const [phone , setPhone]=useState(blogs.phone);
    const [password, setPassword]=useState(blogs.password);

    

    const onchangeHandler=(e)=>{
        if(e.target.name=="name")
        {
            setName(e.target.value);
        }
        else if(e.target.name=="email")
        {
            setEmail(e.target.value);
        }
        else if(e.target.name=="phone")
        {
            setPhone(e.target.value);
        }
        else if(e.target.name=="password")
        {
            setPassword(e.target.value);
        }
    }
    const [error, setError] = useState('');
    const [success, setSuccess] = useState('');
    const onsubmitHandler=(e)=>{
        e.preventDefault();
        const data={id , name , email ,phone , password};
        if(name=="")
        {
            setError("Please enter your name");
        }
        else if(email=="")
        {
            setError("Please enter your email");
        }
        else if(phone=="")
        {
            setError("Please enter your phone");
        }
        else if(password=="")
        {
            setError("Please enter your password");
        }
        else 
        {
            // setSuccess("All field Done");
            fetch("http://localhost:8000/api/user-update", {
            method: "POST", // or 'PUT'
            headers: {
                "Content-Type": "application/json",
            },
            body: JSON.stringify(data),
            })
            .then(response => response.text())
            .then(data => {
                alert(data);
            })
            .catch((error) => {
            console.log('Error : ' , error);
            });
        }
        // console.log(name+" "+email+" "+phone+" "+password);
        
    }
  return (<>
  <Head>
        <title>Update Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
  </Head>
  <div className="row">
    <div className="col-md-6">
    <div className="card">
        <div className="card-body">
            <h5 className="card-title">Update Page</h5>
                {success 
                       ? 
                    <span className="flex items-center text-sm font-bold text-green-700"> 
                        
                         {success}
                    </span> 
                       : 
                    <span className="flex items-center text-sm font-bold text-red-800">
                    
                          {error} 
                    </span>
                }
            
            <form onSubmit={onsubmitHandler}>
            <div className="row">
                <div className="col-md-12">
                    <div className="mb-3">
                        <label for="exampleFormControlInput1" className="form-label">Name</label>
                        <input type="text" className="form-control" name="name" defaultValue={blogs.name} onChange={onchangeHandler} placeholder="Enter Name" />
                        <input type="hidden" className="form-control" name="id" defaultValue={blogs.id}  />
                    </div>
                    <div className="mb-3">
                        <label for="exampleFormControlInput1" className="form-label">Email</label>
                        <input type="email" className="form-control" name="email" defaultValue={blogs.email} onChange={onchangeHandler} placeholder="Enter Email" />
                    </div>
                    <div className="mb-3">
                        <label for="exampleFormControlInput1" className="form-label">Phone No</label>
                        <input type="tel" className="form-control" name="phone" defaultValue={blogs.phone} onChange={onchangeHandler} placeholder="Enter Phone No" />
                    </div>
                    <div className="mb-3">
                        <label for="exampleFormControlInput1" className="form-label">Password</label>
                        <input type="password" className="form-control" name="password" defaultValue={blogs.password} onChange={onchangeHandler} placeholder="Create Password" />
                    </div>
                    <div className="mb-3">
                        <button type="submit" className="btn btn-success">Submit</button>
                    </div>
                </div>
            </div>
            </form>
            
        </div>
        </div>
    </div>
  </div>
  </>
  )
}
